spring:
  application:    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/users/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
          - Path=/ratings/**
          
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates: 
          - Path=/hotels/**
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
okta:
  oauth2:
    issuer: https://dev-77584981.okta.com/oauth2/default
    audience: api://default
    client-id: 00000000000000000000
    client-secret: jjjjjjjjjjjjjjjjjjjjjjjj
    scopes: openid, profile, email, offline_access
    